### ISSUE TITLE
Error instaling...

### ISSUE THREAD

**Issue by drosendo** [socheatsok78/wpml#1]
Im running         "jgrossi/corcel": "^2.4",

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - peakhmr/wpml v1.0.6 requires jgrossi/corcel ^1.4 -> satisfiable by jgrossi/corcel[v1.4.0, v1.4.1, v1.4.2, v1.4.3, v1.4.4, v1.4.5, v1.4.6, v1.4.7] but these conflict with your requirements or minimum-stability.
    - peakhmr/wpml v1.0.5 requires jgrossi/corcel ^1.4 -> satisfiable by jgrossi/corcel[v1.4.0, v1.4.1, v1.4.2, v1.4.3, v1.4.4, v1.4.5, v1.4.6, v1.4.7] but these conflict with your requirements or minimum-stability.
    - peakhmr/wpml v1.0.4 requires jgrossi/corcel ^1.4 -> satisfiable by jgrossi/corcel[v1.4.0, v1.4.1, v1.4.2, v1.4.3, v1.4.4, v1.4.5, v1.4.6, v1.4.7] but these conflict with your requirements or minimum-stability.
    - peakhmr/wpml v1.0.3 requires jgrossi/corcel ^1.4 -> satisfiable by jgrossi/corcel[v1.4.0, v1.4.1, v1.4.2, v1.4.3, v1.4.4, v1.4.5, v1.4.6, v1.4.7] but these conflict with your requirements or minimum-stability.
    - peakhmr/wpml v1.0.2 requires jgrossi/corcel ^1.4 -> satisfiable by jgrossi/corcel[v1.4.0, v1.4.1, v1.4.2, v1.4.3, v1.4.4, v1.4.5, v1.4.6, v1.4.7] but these conflict with your requirements or minimum-stability.
    - peakhmr/wpml v1.0.1 requires jgrossi/corcel ^1.4 -> satisfiable by jgrossi/corcel[v1.4.0, v1.4.1, v1.4.2, v1.4.3, v1.4.4, v1.4.5, v1.4.6, v1.4.7] but these conflict with your requirements or minimum-stability.
    - peakhmr/wpml v1.0.0 requires jgrossi/corcel ^1.4 -> satisfiable by jgrossi/corcel[v1.4.0, v1.4.1, v1.4.2, v1.4.3, v1.4.4, v1.4.5, v1.4.6, v1.4.7] but these conflict with your requirements or minimum-stability.
    - Installation request for peakhmr/wpml ^1.0 -> satisfiable by peakhmr/wpml[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6].

Installation failed, reverting ./composer.json to its original content.`

Is it usable? how?

**Comment by socheatsok78** [comment]
Hold on, i'll take a look into that for you @drosendo

**Comment by socheatsok78** [comment]
I released a new patch, please try installing it again. If you still having problem please let me know.

**Comment by socheatsok78** [comment]
please let me know if the problem still persist

**Comment by drosendo** [comment]
Hey mate!

Thanks for the follow, I will have to give a try later, since I didn't get a response on time, I had to make a work around.

As soon as I have time I will run it.

Cheers,
David

**Comment by socheatsok78** [comment]
@drosendo sure thing. Sorry for the delay by the way.

**Comment by drosendo** [comment]
```
composer require peakhmr/wpml
Using version ^1.0 for peakhmr/wpml
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - peakhmr/wpml v1.0.6 requires jgrossi/corcel ^1.4 -> satisfiable by jgrossi/corcel[v1.4.0, v1.4.1, v1.4.2, v1.4.3, v1.4.4, v1.4.5, v1.4.6, v1.4.7] but these conflict with your requirements or minimum-stability.
    - peakhmr/wpml v1.0.5 requires jgrossi/corcel ^1.4 -> satisfiable by jgrossi/corcel[v1.4.0, v1.4.1, v1.4.2, v1.4.3, v1.4.4, v1.4.5, v1.4.6, v1.4.7] but these conflict with your requirements or minimum-stability.
    - peakhmr/wpml v1.0.4 requires jgrossi/corcel ^1.4 -> satisfiable by jgrossi/corcel[v1.4.0, v1.4.1, v1.4.2, v1.4.3, v1.4.4, v1.4.5, v1.4.6, v1.4.7] but these conflict with your requirements or minimum-stability.
    - peakhmr/wpml v1.0.3 requires jgrossi/corcel ^1.4 -> satisfiable by jgrossi/corcel[v1.4.0, v1.4.1, v1.4.2, v1.4.3, v1.4.4, v1.4.5, v1.4.6, v1.4.7] but these conflict with your requirements or minimum-stability.
    - peakhmr/wpml v1.0.2 requires jgrossi/corcel ^1.4 -> satisfiable by jgrossi/corcel[v1.4.0, v1.4.1, v1.4.2, v1.4.3, v1.4.4, v1.4.5, v1.4.6, v1.4.7] but these conflict with your requirements or minimum-stability.
    - peakhmr/wpml v1.0.1 requires jgrossi/corcel ^1.4 -> satisfiable by jgrossi/corcel[v1.4.0, v1.4.1, v1.4.2, v1.4.3, v1.4.4, v1.4.5, v1.4.6, v1.4.7] but these conflict with your requirements or minimum-stability.
    - peakhmr/wpml v1.0.0 requires jgrossi/corcel ^1.4 -> satisfiable by jgrossi/corcel[v1.4.0, v1.4.1, v1.4.2, v1.4.3, v1.4.4, v1.4.5, v1.4.6, v1.4.7] but these conflict with your requirements or minimum-stability.
    - Installation request for peakhmr/wpml ^1.0 -> satisfiable by peakhmr/wpml[v1.0.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4, v1.0.5, v1.0.6].


Installation failed, reverting ./composer.json to its original content.
```

nope...

**Comment by socheatsok78** [comment]
well why you failed to install it now `Using version ^1.0 for peakhmr/wpml`,
I'll have a look at packagist

**Comment by socheatsok78** [comment]
The webhook that suppose to send a POST request to packagist.org is not working that is why you're not receiving new update.

**Comment by socheatsok78** [comment]
packagis is now showing the new version [v0.1.7](https://github.com/peakhmr/wpml/releases/tag/v1.0.7)

**Comment by drosendo** [comment]
I will have, a go later, my main issue now is will it work with Translated slugs of custom post types.

Original post type: ola
Translated post type slug: hello
?

**Comment by drosendo** [comment]
Something like:

`Post::type($slug)->translate('en')->slug($slug2)->translate('en')->status('publish')->first();`

**Comment by socheatsok78** [comment]
oh you looking for translating url `slug`?

**Comment by socheatsok78** [comment]
can you check this link out?
https://wpml.org/2016/08/how-to-create-and-translate-custom-post-types/

**Comment by socheatsok78** [comment]
I'm not so sure but i don't see any options that WPML allow to translate url `slug` unless you manually changes it in the `New Post` form in the `permalink` input.

**Comment by socheatsok78** [comment]
i'm running on WPML Multilingual CMS `v3.9.1`

**Comment by drosendo** [comment]
![screen shot 2018-01-30 at 15 41 40](https://user-images.githubusercontent.com/884585/35575488-64df4922-05d4-11e8-9bf4-13817173e916.png)
1. WPML > Translation management
2. Tab Multilingual Content Setup
3. Activate "Custom posts slug translation options" hit save
4. Go to "Post Types Translation" on same page and hit "Use different slugs in different languages for SOMETHING"

It will allow you to use a translation for the slug.

**Comment by socheatsok78** [comment]
```php
$slug = urlencode('សាកល្បង');
$postType = \Wpml\Post::type('tips')->slug($slug)->first();
```

I managed to get this running, is that what you looking for?
I never thought of translating url `slug` before that hope this is it.

**Comment by socheatsok78** [comment]
if you know the `slug` string, you don't need to specify the `->translate('en')` at all

**Comment by drosendo** [comment]
Yeah, but also more than translating the slug im translating the "**Costum post type**" slug.

**Comment by socheatsok78** [comment]
this is what i actually see...

![Screen Shot 2018-01-30 at 11.12.31 PM](http://static.gitscout.com/b1168748060c0e2042ab4b5d9ef960062bc2918fe6ab5570d57f810bbc7b71f5.png)

**Comment by socheatsok78** [comment]
i'll check on this more tomorrow, it a little late for me now.
